### ISSUE TITLE
wrong values for 2019 

### ISSUE THREAD

**Issue by sm2607** [oddaspa/easy-exchange-rates#6]
I am using package easy-exchange-rates, but its providing wrong value for few dates can you please suggest what is the issue,for example date 2019-09-30, base currency 'AED' target 'USD'

**Comment by oddaspa** [comment]
Hello @sm2607 ! The source of the data is [https://exchangerate.host/ ](https://exchangerate.host/), so I can not do anything about the data. That being said, I looked into the AED currency and could see that it has some gaps, i.e. missing data. 

AED is missing from the 11th of September 2019 to the 7th of October 2019. Additionally, there is missing data for the 9th of October 2019 and 8th to 11th of November 2019. 

As I said, you need to take that up with Exchange host, but for now I would interpolate the missing values.

Start by getting the currency you want, and AED.

```python
from easy_exchange_rates import API
api = API()
time_series = api.get_exchange_rates(
  base_currency="AED", 
  start_date="2019-09-01", 
  end_date="2019-12-30", 
  targets=["USD", "AED"]
)
```

Convert it to pandas.DataFrame.

```python

data_frame = api.to_dataframe(time_series)
data_frame.plot()
```

<img width="400" alt="Screenshot 2022-12-05 at 13 54 17" src="https://user-images.githubusercontent.com/27822531/205642132-43ecc8a9-dbc8-4d88-a0e2-5577fec01851.png">


Then mask where AED is none and save it to a variable. This variable will now index all the timestamps where AED has missing data.

```python
nans = data_frame["AED"].values != data_frame["AED"].values
```

Use that index to remove the values in USD. (We assume that these values are wrong).

```python
import numpy as np
data_frame[nans] = np.nan
data_frame.plot()
```
<img width="400" alt="Screenshot 2022-12-05 at 13 58 33" src="https://user-images.githubusercontent.com/27822531/205643037-939c152a-db8c-4245-b223-d4817cda45a5.png">

We can then use the pandas interpolate method as such;

```python
data_frame = data_frame.interpolate()
data_frame["USD"].plot()
```
<img width="400" alt="Screenshot 2022-12-05 at 14 02 39" src="https://user-images.githubusercontent.com/27822531/205643842-5b15301c-eb25-4089-959d-52fd9ee45915.png">

**Comment by sm2607** [comment]
hi @oddaspa thankyou so much for this clarification and workaround suggestion and will implement this.
