### ISSUE TITLE
get_exchange_rates does not work

### ISSUE THREAD

**Issue by ThibaultDC** [oddaspa/easy-exchange-rates#7]
Using get_exchange_rates returns the following error: 

> {'success': False, 'error': {'code': 101, 'type': 'missing_access_key', 'info': 'You have not supplied an API Access Key. [Required format: access_key=YOUR_ACCESS_KEY]'}}

**Comment by oddaspa** [comment]
Hi @ThibaultDC !

It seems like [https://exchangerate.host/](https://exchangerate.host/) has started requiring API keys, as well as rate limiting. This means that you would need to sign up on their website to get a key for their API. I have not implemented this in the package.

**Comment by oddaspa** [comment]
Hi again @ThibaultDC !

I have just pushed version 0.2 #8. I swapped the API to get data directly from the European Central Bank, thus avoiding having to pay Exchangerate.host. I have also changed the main method to directly output a dataframe, skipping an unneccesary step.
